TwitterAutoReply() {
	@twitter.source(text, _, _, from, _, _), $regex(text, "FrankWang2013") => 
	@$notify("You are mentioned by " + from + ": " + text);
	@twitter.source(text, _, _, from, _, _), $regex(text, "FrankWang2013") => 
	@twitter.sink("Hey @" + from + "! What's up? (automatically generated by Sabrina.)");
}