TwitterAutoReply() {
	var autoReplyOn : Boolean;
	@sabrina.listen(expression), $regex(expression, "auto reply on", "i") => autoReplyOn(true);
	@sabrina.listen(expression), $regex(expression, "auto reply on", "i") => @sabrina.say("Auto Reply is Now On \n");
	@sabrina.listen(expression), $regex(expression, "auto reply off", "i") => autoReplyOn(false);
	@sabrina.listen(expression), $regex(expression, "auto reply off", "i") => @sabrina.say("Auto Reply is Now Off \n");

	@twitter.source(text, _, _, from, _, _), $regex(text, "FrankWang2013"), autoReplyOn(true) => 
	@$notify("You are mentioned by " + from + ": " + text + "\n auto replying... \n");
	@twitter.source(text, _, _, from, _, _), $regex(text, "FrankWang2013"), autoReplyOn(false) => 
	@$notify("You are mentioned by " + from + ": " + text + "\n no auto reply \n");
	@twitter.source(text, _, _, from, _, _), $regex(text, "FrankWang2013"),  autoReplyOn(true) => 
	@twitter.sink("Hey @" + from + "! What's up? (automatically generated by Sabrina. \n)");
}